# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dI6AiQIKGCW2cO29uvfVsfynGgK_qvps
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/sample_data/final_dataset.csv')

"""# New Section"""

df.describe()

df.columns

# df = df.drop(['id', ],axis=1)
# df

x = df.isna().sum()

# x['host_location']
x['city']

# df1 = df.dropna(subset = ['host_location'])
df1=df.dropna(subset=['city'])

df1.shape

#g = df1.groupby('host_location').size()
# g = df1.groupby("host_location", group_keys=True).apply(lambda x: x)
g = df1.groupby("city", group_keys=True).apply(lambda x: x)

# s = set(g['host_location'])
s = set(g['city'])

len(s)

#x = g[g['host_location'] == "San Jose, CA"]
x = []
loc = []
len_loc = []
for i in s:
  x.append(g[g['city'] == i]['availability_365'].sum())
  print(len(g[g['city'] == i]))
  len_loc.append(len(g[g['city'] == i]))
  loc.append(i)

len(len_loc)

idx = loc.index('Palo Alto')

loc

len_loc[idx]

z=[]
for i in range(0,len(x)):
  y = (365*len_loc[i] - x[i])
  z.append(y)

idx = loc.index('Palo Alto')
z[idx]

avg_booking = z[idx]/(len_loc[idx]*365)

avg_booking = avg_booking*100

avg_booking

